services: 
  database: 
    image: mongo
    container_name: mongodb
    ports: 
      - "27017:27017"
  application:
    image: file2finance
    container_name: file2finance
    links: 
      - database
    depends_on: 
      - database
    ports: 
      - "8080:8080"
